[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/encode/base64"
  to = "/.netlify/functions/encode-base64"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/decode/base64"
  to = "/.netlify/functions/decode-base64"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/utilities/hash/md5"
  to = "/.netlify/functions/hash-md5"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/encode/url"
  to = "/.netlify/functions/encode-url"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/decode/url"
  to = "/.netlify/functions/decode-url"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/utilities/uuid"
  to = "/.netlify/functions/generate-uuid"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/encode/hex"
  to = "/.netlify/functions/encode-hex"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/decode/hex"
  to = "/.netlify/functions/decode-hex"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/utilities/hash/sha256"
  to = "/.netlify/functions/hash-sha256"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/utilities/timestamp"
  to = "/.netlify/functions/timestamp"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]
