[build]
  functions = "netlify/functions"
  command = "npx @openapitools/openapi-generator-cli generate -i index.json -g html2 -o docs-temp && cp docs-temp/index.html index.html && rm -rf docs-temp"
  [build.environment]
    JAVA_VERSION = "17"
    NODE_VERSION = "20"

[[redirects]]
  from = "/encode-base64"
  to = "/.netlify/functions/encode-base64"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/decode-base64"
  to = "/.netlify/functions/decode-base64"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/hash-md5"
  to = "/.netlify/functions/hash-md5"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/encode-url"
  to = "/.netlify/functions/encode-url"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/decode-url"
  to = "/.netlify/functions/decode-url"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]

[[redirects]]
  from = "/generate-uuid"
  to = "/.netlify/functions/generate-uuid"
  status = 200
  methods = ["GET", "POST", "OPTIONS"]
